scripts/chicago-staging-crontasks
This PR deals with the first second checkbox in this meta-issue: datamade/django-councilmatic#182
=> Give an age and batch size to the staging update_index

scripts/chicago-crontasks, scripts/chicago-staging-crontasks
This PR turns off cron in preparation for running migrations against the Councilmatic database. Relates to: datamade/scrapers-us-municipal#12
=> Turn off cron

chicago/search_indexes.py
See title. This change is in line with the upstream `prepare_last_action_date` in `django-councilmatic`. See explanatory comment in this commit: https://github.com/datamade/django-councilmatic/commit/289d629efa3a14ee1dd1e58b9def81f1603542bf.
Handles #265.
I tested this locally using our fancy schmancy Docker setup.
=> Return dates from prepare_last_action_date

scripts/chicago-crontasks
When we launched the Councilmatic upgrade, we broke the production cronjob with invalid syntax. This is the cause of #275: we have the legislation, but our cron to add it to the search index has not been running. This PR fixes the cron.
I made this change in place on the server and confirmed it ran:
```
ubuntu@ip-10-0-0-124:~$ grep CRON /var/log/syslog | tail
...
Sep  9 19:45:01 ip-10-0-0-124 CRON[25226]: (datamade) CMD (/usr/bin/flock -n /tmp/chicago_dataload.lock -c 'cd $APPDIR && $PYTHONDIR manage.py update_index --batch-size=50 --age=1 >> /var/log/councilmatic/chicago-updateindex.log 2>&1')
ubuntu@ip-10-0-0-124:~$ tail -f /var/log/councilmatic/chicago-updateindex.log
[14:45:06][INFO] pysolr pysolr.py:_send_request:402 | Finished 'http://127.0.0.1:8983/solr/chicago/update/?commit=true' …
```
=> Fix production crontask

chicago/templates/event.html, chicago/views.py
Adds alder attendance to events.
I'm deciding between two layouts:
Which is better? Also, is it worth it to include Alder headshots on this list?
To do:
- some events show all participants are absent: http://localhost:8000/event/committee-on-transportation-and-public-0dba80f90653/
- some events throw an `AttributeError` for missing person ID: http://localhost:8000/event/committee-on-economic-capital-and-9b249e191988/
Closes #301
=> adds roll call to events

chicago/templates/event.html, chicago/templates/events.html, chicago/templates/partials/event_time_item.html, chicago/views.py
* closes #309 
* closes #310 
* restores links to legistar and document links with ocd model updates, related to #299 
* adds previous and next month buttons to events page, brings in events view code from `django-councilmatic`
=> Attendance updates

chicago/templates/person.html, chicago/views.py
Following on from #316 and #308, adds a table to show event attendance for all alderpersons based on their committee memberships.
A few things to address:
- there may be a more efficient way to make this query. it does seem a bit expensive
- this code doesn't account for committee tenure and is incorrectly marking absences for older events. could use another look to figure out a way to get this in the events query
=> add attendance tab to alder pages

README.md, chicago/templates/base.html, chicago/templates/legislation.html, chicago/views.py
Was able to pull the latest data from production and update the README instructions for others with access to reproduce.
This PR is a first pass at representing votes for actions related to bills. It shows a total along with the list of voters with links to their profiles. Totals are grouped by "Votes for", "Votes against" and "Other votes" which include "Absent", "Not voting" and everything else.
Here's a few examples:
Ordinance O2017-2027: Amendment of Municipal Code Title 2 by removing individuals retained as independent contractors from definition of "City employee" and "City Council employee" (failed)
Routine committee vote on Ordinance O2011-3749 with a committee vote and a full council vote
There are a lot of votes that are 45+ votes in favor, which makes the list quite long. …
=> Bill votes

chicago/models.py, chicago/templates/person.html, chicago/views.py
Resolves https://sentry.io/organizations/datamade/issues/3858894029/?project=63977 by using `ChicagoPerson.attendance_percent` in template
Also adds some template logic to handle display of term dates and titles for former Aldermen.
=> handle term dates for former alds

chicago/templates/about.html, chicago/templates/base.html, chicago/templates/committee.html, chicago/templates/committees.html, chicago/templates/compare_council_members.html, chicago/templates/council_members.html, chicago/templates/divided_votes.html, chicago/templates/index.html, chicago/templates/person.html, councilmatic/settings.py
We were using `adv_cache_tag` to wrap select blocks to be cached with a custom tag name and expire time. This led to lots of extra block tags and some pages with no caching at all. Now that we're not using notifications, we can just use the middleware caching for all pages instead. This PR makes that change.
=> Simplify cache

chicago/templates/base_with_margins.html, chicago/templates/divided_votes.html, councilmatic/settings.py
Divided votes has quite a few columns that aren't really useful to sort/filter on. This PR removes them.
Additionally I updated cache timeout to 6 hours (was 5 min by default) and removed some additional margins in the base page
=> chache and mobile improvements for divided votes

README.md, chicago/templates/about.html, councilmatic/settings.py
This increases the cache timeout from 6 hours to 24 hours to improve performance.
Related to https://github.com/datamade/chicago-council-scrapers/pull/5, which should be brought in at the same time.
This PR also updates the README and about pages linking to the datasette download link and chicago-council-scrapers repo. Closes #332
=> cache site for 24 hours

chicago/models.py, chicago/templates/person.html, chicago/templatetags/chicago_extras.py
Resolves two classes of errors we've been encountering:
- inactive people with no `latest_council_membership` (like Former Mayor Daley)
https://chicago.councilmatic.org/person/daley-richard-m-99518b1b825d/
- no `person` object for some inactive people 
https://chicago.councilmatic.org/legislation/o2015-3676/
https://chicago.councilmatic.org/legislation/r2014-358/
https://chicago.councilmatic.org/legislation/o2016-8592/
- also hides the committee and attendance tabs on the person page when these values are zero
=> patch for missing person attributes

chicago/templates/base.html, chicago/views.py, councilmatic/urls.py
Substitute ordinances no longer need redirects in the new LMS. Removed the redirect logic.
We're also getting data from the new system, so removed the data banner.
=> removed data banner, removed substitute redirect view and url

chicago/templates/base.html, chicago/templates/council_members.html, chicago/templates/updates.html, chicago/views.py, councilmatic/urls.py
Adds new updates page to start logging changes we make to Chicago Councilmatic. I added 3 recent entries on switching to the new clerk LMS and addressing identifier redirects.
=> add updates page with 3 recent entries

chicago/models.py, chicago/templates/event.html, chicago/templates/legislation.html, chicago/templates/partials/seo.html, chicago/views.py
For events with Vimeo links, shows that as an embed at the top:
Formats the agenda as a table with links to ordinances and sponsors:
=> better event page: vimeo embed, event agenda

chicago/templates/event.html, chicago/templates/legislation.html
* Fix for and closes #363 
* Partial fix for for #366
=> Sept 22 updates

chicago/static/css/custom.css, chicago/templates/event.html, chicago/templates/legislation.html, chicago/templatetags/chicago_extras.py
Applies card styles for tables in mobile mode as mentioned in https://github.com/datamade/how-to/issues/350
For screens smaller than 768px (`xs` on Bootstrap 3), table rows are rendered as cards for both meeting agendas and legislative actions:
Meeting agenda:
Legislation action:
This PR also cleans up some redundant css classes and:
- better presents responsive vimeo iframes. related to #359 
- logic update for getting source link. fix again for #362
=> Render tables as cards on mobile

chicago/templates/robots.txt, chicago/views.py, chicago/views_sitemaps.py, councilmatic/settings.py, councilmatic/urls.py, robots.txt
Django has a pretty robust sitemap framework that supports multiple sections and pagination. This is necessary for indexing our bills, of which we have over 150,000 of. https://docs.djangoproject.com/en/3.2/ref/contrib/sitemaps/
* adds a cached `sitemaps.xml` with an index of sitemaps, including paginated sitemap for legislation. closes #384 
* adds robots.txt
=> dynamic, paginated sitemap

chicago/feeds.py, chicago/models.py, chicago/views.py
* resolves https://datamade.sentry.io/issues/4748169564/?project=63977&query=&referrer=project-issue-stream
* overriding `primary_sponsorships` property in `ChicagoPerson` and sorting in the query
* updates person view to use this attribute for consistency
=> primary_sponsorships refactor

.flake8, chicago/feeds.py, chicago/urls.py, chicago/views.py, pytest.ini, setup.cfg
Updates `urls.py` to properly route to search rss.
Reverts `flake8` config settings
Closes #397
=> search RSS fix

chicago/management/commands/preview_search_text.py, chicago/search_indexes.py, chicago/templates/feeds/search_item_description.html, chicago/templates/search/bill_text.txt, chicago/templatetags/extras.py
This had some out of date references which was causing the full text search to miss bills like in #388.
closes #388
I also added a management command to preview the content that will be search to the search enginge.
```
python manage.py preview_search_text R2023-0004166
```
Before the changes this is what would have been sent:
```python
{   'abstract': '',
'actions': [   'R2023-0004166 action on 2023-09-14',
'R2023-0004166 action on 2023-09-14',
'R2023-0004166 action on 2023-11-01',
'R2023-0004166 action on 2023-11-01',
'R2023-0004166 action on 2023-11-07'],
'bill_type': 'resolution',
'bill_type_exact': None,
'boost': 1.095890410958904,
'controlling_body': ['Chicago City Council'],
'controlling_body_exact': None,
'description': 'Submission of public question by referendum to Chicago ' …
```
=> fix bill_text template

chicago/feeds.py, chicago/templates/committee.html, chicago/templates/compare_council_members.html, chicago/templates/event.html, chicago/templates/events.html, chicago/templates/legislation.html, chicago/templates/partials/committee_person_table.html, chicago/templates/partials/component_upcoming_events.html, chicago/templates/partials/council_member_table.html, chicago/templates/search/search.html
Search results were not filtering in RSS. Closes #199
Also found and removed additional references ti `CITY_VOCAB` that were removed in #392
=> fix rss for search, removed CITY_VOCAB references

chicago/views_sitemaps.py
https://chicago.councilmatic.org/sitemap-static.xml is currently broken. this will fix it.
=> we don't need this namespace anymore

chicago/feeds.py, chicago/views.py
Handles the following sentry errors:
* https://datamade.sentry.io/issues/4820142834/?project=63977
* https://datamade.sentry.io/issues/4505824150/?project=63977
=> handling some AttributeErrors

README.md, chicago/models.py, chicago/templates/about.html, chicago/templates/legislation.html, chicago/templates/partials/legislation_text.html, chicago/templatetags/extras.py
* listing legislative documents in addition to the ordinance, when present, closes #413 
* adds a `proxy_url` template tag
* unrelated, also updates the puddle link to the datamade.us domain.
Example: o2024-0007772
=> list additional document attachments

chicago/static/css/custom.css, chicago/templates/compare_council_members.html, chicago/templates/person.html
- adds styles for readability on the 'Processing...' message for DataTables
- better alignment for `nav-pils` on mobile
- adds `rows-and-columns` styles to campaign donations table for better mobile display
- adds `rows-and-columns` styles to compare alders page
=> Mobile styles for alder donations and compare alder page
